#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server.
#Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY.
argument_count=$#
if [ "$argument_count" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [ "$argument_count" -gt 3 ]; then
		scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
	else
		scp -o StrictHostKeyChecking=no "$1" "$3"@"$2"~/
	fi
fi
