#!/usr/bin/env bash
#A script that installs nginx and start the service and adds redirection and
#custom 404 page and a custom HTTP header stating hostname of server.

#install nginx
  apt-get update
  apt-get -y install nginx
#create custom page
  echo "Hello World!" > /var/www/html/index.html
#create redirection for /redirect_me
  sed -i "/^\tlocation \/ {/a \ \t\trewrite ^/redirect_me \$scheme://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
#create custom 404 settings and custom 404 page
  echo -e "\n\terror_page 404 /custom_404.html;\n\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" > mysettings
  sed -i "/^\tserver_name _;/r mysettings" /etc/nginx/sites-available/default
  rm mysettings
  echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
#create custom HTTP header identifying server hostname
#shellcheck disable=SC2154
  hostname=$(hostname)
  sed -i "/^\tlocation \/ {/a \ \t\tadd_header X-Served-By \"$hostname\";" /etc/nginx/sites-available/default
  unset hostname
ufw allow 'Nginx HTTP'
service nginx start
