#!/usr/bin/env bash
#Prints FizzBuzz if divisible by 3 and 5, Fizz if by only 3 and Buzz if
#divisible by 5 only
for ((i=1; i<=100; i++))
do
	if (( i % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
