#!/usr/bin/env bash
# This script displays "Best School" 10 times but substitute "bad luck" at 4th
# position and "good luck" at 8th position.
count=1
while [ "$count" -le 10 ]
do
	if [ "$count" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$count" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
((count++))
done
#end of script.
