#!/usr/bin/env bash
# This script displays a number count from 1 - 20, but "bad luck from china" is
# added after position 4, "bad luck from Japan" after position 9 and
# "bad luck from Italy" at 17th position.
count=1
while [ "$count" -le 20 ]
do
case "$count" in
4)
	echo "$count"
	echo "bad luck from China"
	;;
9)
	echo "$count"
	echo "bad luck from Japan"
	;;
17)
	echo "$count"
	echo "bad luck from Italy"
	;;
*)
	echo "$count"
	;;
esac
((count++))
done
#end of script.
