#!/usr/bin/env bash
# A bash script that configures an Ubuntu server to resolve
# localhost to 127.0.0.2 and resolves facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
#rm ~/hosts.new
